### ISSUE TITLE
process: consolidate the default middlewares into a single module

### ISSUE THREAD

**Issue by sio4** [gobuffalo/middleware#1]
As of today, we have 7 official middleware modules and 4 of them are used in a new app by default. Now, these middleware are stable and have no much update recently except dependency updates. To reduce the maintenance effort on these modules, and also to simplify the module dependency structure, I would like to consolidate the default middleware (which are `mw-csrf`, `mw-forcessl`, `mw-i18n`, and `mw-paramlogger`) into a single module. Each of them will be a separate package in the module but will share the same module version and other stuff.

The process will be:
* [x] prepare the new module by merging them all together into this repository
* [x] update and clean up all the old modules before deprecating them, and releasing them as the last versions.
* [x] improve the CLI to use the new module for a new app
* [x] improve the CLI fixer to update existing apps, but this is optional
* --> CLI v0.18.14 was released with this update

Hey @paganotoni, as we discussed before, I am going to deprecate the old default middleware modules (4 modules) and merge them into this module. Please take a look at the rough process above and let me know if you have any concern or comment on it. ETA for this work is the end of this month roughly.

Related tasks:
* [x] gobuffalo/mw-paramlogger/pull/12
* [x] gobuffalo/mw-i18n/pull/36
* [x] gobuffalo/mw-forcessl/pull/4
* [x] gobuffalo/mw-csrf/pull/15
* [x] gobuffalo/mw-contenttype/pull/3
* [x] gobuffalo/cli/pull/253

**Comment by paganotoni** [comment]
I'm glad you brought this one up, and I appreciate what you're doing here. This will make our codebase way simpler.

**Comment by sio4** [comment]
Completed!
